### ISSUE TITLE
Issues Updating to 0.1.2

### ISSUE THREAD

**Issue by earthtone** [vue-styleguidist/vue-cli-plugin-styleguidist#11]
Running the styleguide script (to run the styleguide from a local server) after updating from version `0.1` to `0.1.2` throws the following error:

```sh
true 'StyleguidistError'
Unknown config option ignore was found, the value is:
[
  '**/components/order/CartSidebar.vue'
]
undefined
```

After commenting out the `ignore` configuration option, running the script works, but logs the following warning:

```sh
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.

Warning: Cannot parse src/components/cards/CardCategory.vue: Error: Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
```

The styleguide is then able to be generated as expected, without the first component indicated in the warning, regardless of what that first component is. I've tried excluding several components now, which is not easy considering the `ignore` option is no longer supported, and I get the same warning pointing to whichever component is the first to be ingested by the plugin.

I'm trying to include this in a project generated with `vue-cli v3.0.1` with [these config options, scripts & dependencies](https://gist.github.com/earthtone/f2ce61c5946c36409d4b40c3fe55dcc1). Is there some conflict in my project I should be aware of? Is there a less invasive way of addressing these errors and warnings, since this is an organization project and I do not have a lot of freedom to update dependencies wildly.

If this is not a genuine bug I'd personally consider an API change and a dependency update that requires consumers to update their projects' dependencies a *breaking* change, not a _patch_, as indicated by the update in version number.

**Comment by elevatebart** [comment]
Hey @earthtone, have a looksie at this bug vue-styleguidist/vue-styleguidist#191.
I believe this would solve your ignore problem.
As soon as @rafaesc has release vue-styleguidist I will release the plugin.

**Comment by elevatebart** [comment]
I am investigating the same babel issue in my repo. 
It seems to be due to the use of jest and its delayed update to babel 7.
Still looking into it.

**Comment by raulmelo** [comment]
Okay, I'll run some tests to try to help you.
😁👍

**Comment by elevatebart** [comment]
Just pusblished v0.1.3 with the ignore fix

**Comment by mqqza** [comment]
[Vue-docgen-api](https://github.com/vue-styleguidist/vue-docgen-api) was updated but cli version oldest.

Solution: install vue-docgen-api manualy

**Comment by elevatebart** [comment]
Hey @earthtone, 
Do you mind if I close this issue as it seems to be fixed and delivered?
