### ISSUE TITLE
vue-styleguidist version bump

### ISSUE THREAD

**Issue by 2xAA** [vue-styleguidist/vue-cli-plugin-styleguidist#33]
This repo's version of vue-styleguidist is on 3.0.9 when vue-styleguidist is on 3.0.15.
Can we get a version update, please?

**Comment by elevatebart** [comment]
I hope we will get to a monorepo soon so that all releases are done at the same time ;)

**Comment by 2xAA** [comment]
Me too 😅

**Comment by elevatebart** [comment]
delivered !! ;)
