### ISSUE TITLE
Adding the plugin removes integral parts of the existing package.json

### ISSUE THREAD

**Issue by andreasvirkus** [vue-styleguidist/vue-cli-plugin-styleguidist#34]
Hi there, I'll just let the `git diff` comparison talk for itself:

```
"private": true,
   "scripts": {
     "serve": "vue-cli-service serve",
-    "build:demo": "vue-cli-service build",
     "build": "vue-cli-service build --target lib --name Kibble src/index.js",
     "lint": "vue-cli-service lint",
-    "test:unit": "vue-cli-service test:unit"
-  },
-  "main": "dist/YourLib.umd.js",
-  "unpkg": "dist/YourLib.umd.min.js",
-  "jsDelivr": "dist/YourLib.umd.min.js",
-  "files": ["dist", "src"],
-  "peerDependencies": {
-    "vue": "^2.6.0"
+    "build:demo": "vue-cli-service build",
+    "test:unit": "vue-cli-service test:unit",
+    "styleguide": "vue-cli-service styleguidist",
+    "styleguide:build": "vue-cli-service styleguidist:build"
   },
```

It seems that it searches for the first script starting with "build" and then injects the styleguidist's scripts after it? This, however, removes a big chunk of my exisitng package.json.

The only modifications that I've made to a vanilla `vue-cli` setup are the ones that Linus suggested here for setting up a component library package: https://twitter.com/Linus_Borg/status/1097554989407440896

(slides [#19](https://speakerdeck.com/linusborg/building-components-with-vue-cli-3?slide=19) and [#21](https://speakerdeck.com/linusborg/building-components-with-vue-cli-3?slide=21))

**Comment by elevatebart** [comment]
Hello @andreasvirkus Can you send the rest of your diff? I think that your updates are not removed but simply moved by the CLI. 
What I do is simply use extendPackage function which will not remove lines from a file.
https://github.com/vuejs/vue-cli/blob/3f434f69c6bbff3d6969126544c0bd0128135d33/packages/%40vue/cli/lib/GeneratorAPI.js#L126-L150

**Comment by elevatebart** [comment]
CF tests added in the linked PR #39

**Comment by elevatebart** [comment]
This is my attempt at reproducing your bug...
https://github.com/elevatebart/test-vue-lib

**Comment by elevatebart** [comment]
As you can seen [here](https://github.com/elevatebart/test-vue-lib/commit/aa20999cee6b8a443e3021f97ec332ff19a2cf82#diff-b9cfc7f2cdf78a7f4b91a753d10865a2) adding the plugin simply moves the keys. 
I believe that is uncool, and will send a quick PR to the @vue/cli.
But this does not qualify as a bug. 

Please tell me if I am mising something.

**Comment by elevatebart** [comment]
These updates are actually intentional, some keys were actually forgotten though.
This reorder allows for some kind of consistency between vue cli projects. 
It does not seem to be a bug.

Hope this helps.
Bart

**Comment by andreasvirkus** [comment]
Hi Bart,

Sorry - it does indeed seem that they were simply appended to the bottom/reordered.
I'd say it's a weird behaviour though since most people would want/need to still order them back afterwards (since the best practise seems to be that all different types of dependencies are listed in sequence, your `main` entrypoint is usually defined quite at the top, etc.)

Thanks for looking into this though and sorry for the trouble
