### ISSUE TITLE
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3"

### ISSUE THREAD

**Issue by PhmNgocNghia** [vue-styleguidist/vue-cli-plugin-styleguidist#9]
Vue CLI version: 3.0.1
Reproduce step
- vue create my-project
- cd my-project
- vue add styleguidist
- yarn styleguide

`Error: can't find vue loader`

- yarn add vue-loader
- yarn styleguide

`It' work but : We couldn’t find any components using these patterns:`
- edit styleguide.config.js
- add: ` components: 'src/components/**/[A-Z]*.vue',`

`Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspec
t the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.`

**Comment by rafaesc** [comment]
It has reference with  https://github.com/vue-styleguidist/vue-docgen-api/issues/48
